// <auto-generated />
using System;
using AleutStaffing.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AleutStaffing.Infrastructure.Migrations
{
    [DbContext(typeof(AleutStaffingDbContext))]
    [Migration("20251118230729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AleutStaffing.Core.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationPct")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_pct");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPtoOrTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pto_or_training");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("ProjectRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_role_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_assignments_approved_by_user_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_assignments_person_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("ix_assignments_project_role_id");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_assignments_start_date_end_date");

                    b.HasIndex("WbsElementId", "Status")
                        .HasDatabaseName("ix_assignments_wbs_element_id_status");

                    b.HasIndex("TenantId", "PersonId", "Status")
                        .HasDatabaseName("ix_assignments_tenant_id_person_id_status");

                    b.ToTable("assignments");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.AssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationPct")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_pct");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_history");

                    b.HasIndex("AssignmentId", "ChangedAt")
                        .HasDatabaseName("ix_assignment_history_assignment_id_changed_at");

                    b.ToTable("assignment_history");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("EndDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bookings_tenant_id");

                    b.HasIndex("PersonId", "Status")
                        .HasDatabaseName("ix_bookings_person_id_status");

                    b.HasIndex("SpaceId", "StartDatetime", "EndDatetime")
                        .HasDatabaseName("ix_bookings_space_id_start_datetime_end_datetime");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Issuer")
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_certifications");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_certifications_name");

                    b.ToTable("certifications");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.CheckInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("processed_by_user_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_check_in_events");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_check_in_events_booking_id");

                    b.ToTable("check_in_events");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_offices");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_offices_tenant_id_status");

                    b.ToTable("offices");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text")
                        .HasColumnName("cost_center");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("LaborCategory")
                        .HasColumnType("text")
                        .HasColumnName("labor_category");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrgUnit")
                        .HasColumnType("text")
                        .HasColumnName("org_unit");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_people_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_people_user_id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_people_tenant_id_email");

                    b.ToTable("people");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.PersonCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("certification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CredentialId")
                        .HasColumnType("text")
                        .HasColumnName("credential_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_person_certifications");

                    b.HasIndex("CertificationId")
                        .HasDatabaseName("ix_person_certifications_certification_id");

                    b.HasIndex("PersonId", "CertificationId")
                        .HasDatabaseName("ix_person_certifications_person_id_certification_id");

                    b.ToTable("person_certifications");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.PersonSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_person_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_person_skills_skill_id");

                    b.HasIndex("PersonId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_skills_person_id_skill_id");

                    b.ToTable("person_skills");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ProgramCode")
                        .HasDatabaseName("ix_projects_program_code");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_projects_tenant_id_status");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowSelfRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_self_request");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("FteRequired")
                        .HasColumnType("numeric")
                        .HasColumnName("fte_required");

                    b.Property<string>("LaborCategory")
                        .HasColumnType("text")
                        .HasColumnName("labor_category");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("text")
                        .HasColumnName("required_skills");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("WbsElementId")
                        .HasDatabaseName("ix_project_roles_wbs_element_id");

                    b.HasIndex("TenantId", "WbsElementId", "Status")
                        .HasDatabaseName("ix_project_roles_tenant_id_wbs_element_id_status");

                    b.ToTable("project_roles");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalFields")
                        .HasColumnType("text")
                        .HasColumnName("additional_fields");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_section_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_entries");

                    b.HasIndex("ResumeSectionId")
                        .HasDatabaseName("ix_resume_entries_resume_section_id");

                    b.ToTable("resume_entries");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("TemplateConfig")
                        .HasColumnType("text")
                        .HasColumnName("template_config");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_profiles");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_resume_profiles_person_id");

                    b.ToTable("resume_profiles");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("ResumeProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_profile_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_sections");

                    b.HasIndex("ResumeProfileId")
                        .HasDatabaseName("ix_resume_sections_resume_profile_id");

                    b.HasIndex("PersonId", "DisplayOrder")
                        .HasDatabaseName("ix_resume_sections_person_id_display_order");

                    b.ToTable("resume_sections");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_assignments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_assignments_user_id");

                    b.HasIndex("TenantId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_role_assignments_tenant_id_user_id_role");

                    b.ToTable("role_assignments");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("OfficeId")
                        .HasDatabaseName("ix_spaces_office_id");

                    b.HasIndex("TenantId", "OfficeId", "Type")
                        .HasDatabaseName("ix_spaces_tenant_id_office_id_type");

                    b.ToTable("spaces");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_object_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId", "EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_entra_object_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.WbsElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billable");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_wbs_elements");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_wbs_elements_project_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_wbs_elements_tenant_id_code");

                    b.ToTable("wbs_elements");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Assignment", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments__users_approved_by_user_id");

                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithMany("Assignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__people_person_id");

                    b.HasOne("AleutStaffing.Core.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments__project_roles_project_role_id");

                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__tenants_tenant_id");

                    b.HasOne("AleutStaffing.Core.Entities.WbsElement", "WbsElement")
                        .WithMany("Assignments")
                        .HasForeignKey("WbsElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__wbs_elements_wbs_element_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Person");

                    b.Navigation("ProjectRole");

                    b.Navigation("Tenant");

                    b.Navigation("WbsElement");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.AssignmentHistory", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Assignment", "Assignment")
                        .WithMany("History")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_history_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Booking", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithMany("Bookings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__people_person_id");

                    b.HasOne("AleutStaffing.Core.Entities.Space", "Space")
                        .WithMany("Bookings")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__spaces_space_id");

                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__tenants_tenant_id");

                    b.Navigation("Person");

                    b.Navigation("Space");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.CheckInEvent", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Booking", "Booking")
                        .WithMany("CheckInEvents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_events_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Office", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offices__tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Person", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany("People")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_people__tenants_tenant_id");

                    b.HasOne("AleutStaffing.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_people__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.PersonCertification", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Certification", "Certification")
                        .WithMany("PersonCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_certifications_certifications_certification_id");

                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithMany("PersonCertifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_certifications_people_person_id");

                    b.Navigation("Certification");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.PersonSkill", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithMany("PersonSkills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_skills_people_person_id");

                    b.HasOne("AleutStaffing.Core.Entities.Skill", "Skill")
                        .WithMany("PersonSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_skills__skills_skill_id");

                    b.Navigation("Person");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Project", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects__tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ProjectRole", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_roles__tenants_tenant_id");

                    b.HasOne("AleutStaffing.Core.Entities.WbsElement", "WbsElement")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("WbsElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_roles__wbs_elements_wbs_element_id");

                    b.Navigation("Tenant");

                    b.Navigation("WbsElement");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeEntry", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.ResumeSection", "ResumeSection")
                        .WithMany("Entries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_entries__resume_sections_resume_section_id");

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeProfile", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithOne("ResumeProfile")
                        .HasForeignKey("AleutStaffing.Core.Entities.ResumeProfile", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_profiles_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeSection", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_sections_people_person_id");

                    b.HasOne("AleutStaffing.Core.Entities.ResumeProfile", null)
                        .WithMany("Sections")
                        .HasForeignKey("ResumeProfileId")
                        .HasConstraintName("fk_resume_sections_resume_profiles_resume_profile_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.RoleAssignment", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments__tenants_tenant_id");

                    b.HasOne("AleutStaffing.Core.Entities.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Space", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Office", "Office")
                        .WithMany("Spaces")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_offices_office_id");

                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces__tenants_tenant_id");

                    b.Navigation("Office");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.User", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.WbsElement", b =>
                {
                    b.HasOne("AleutStaffing.Core.Entities.Project", "Project")
                        .WithMany("WbsElements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_elements_projects_project_id");

                    b.HasOne("AleutStaffing.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_elements_tenants_tenant_id");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Assignment", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Booking", b =>
                {
                    b.Navigation("CheckInEvents");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Certification", b =>
                {
                    b.Navigation("PersonCertifications");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Office", b =>
                {
                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Person", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Bookings");

                    b.Navigation("PersonCertifications");

                    b.Navigation("PersonSkills");

                    b.Navigation("ResumeProfile");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Project", b =>
                {
                    b.Navigation("WbsElements");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ProjectRole", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeProfile", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.ResumeSection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Skill", b =>
                {
                    b.Navigation("PersonSkills");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Space", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.Tenant", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.User", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("AleutStaffing.Core.Entities.WbsElement", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ProjectRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
