// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyScheduling.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyScheduling.Infrastructure.Migrations
{
    [DbContext(typeof(MySchedulingDbContext))]
    [Migration("20251120122741_EnhanceFacilitiesManagement")]
    partial class EnhanceFacilitiesManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyScheduling.Core.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationPct")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_pct");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPtoOrTraining")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pto_or_training");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("ProjectRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_role_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_assignments_approved_by_user_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_assignments_person_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("ix_assignments_project_role_id");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_assignments_start_date_end_date");

                    b.HasIndex("WbsElementId", "Status")
                        .HasDatabaseName("ix_assignments_wbs_element_id_status");

                    b.HasIndex("TenantId", "PersonId", "Status")
                        .HasDatabaseName("ix_assignments_tenant_id_person_id_status");

                    b.ToTable("assignments");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.AssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationPct")
                        .HasColumnType("integer")
                        .HasColumnName("allocation_pct");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text")
                        .HasColumnName("change_reason");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_history");

                    b.HasIndex("AssignmentId", "ChangedAt")
                        .HasDatabaseName("ix_assignment_history_assignment_id_changed_at");

                    b.ToTable("assignment_history");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("EndDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bookings_tenant_id");

                    b.HasIndex("PersonId", "Status")
                        .HasDatabaseName("ix_bookings_person_id_status");

                    b.HasIndex("SpaceId", "StartDatetime", "EndDatetime")
                        .HasDatabaseName("ix_bookings_space_id_start_datetime_end_datetime");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Issuer")
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_certifications");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_certifications_name");

                    b.ToTable("certifications");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.CheckInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("processed_by_user_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_check_in_events");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_check_in_events_booking_id");

                    b.ToTable("check_in_events");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.FacilityPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<int?>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_facility_permissions");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_facility_permissions_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_facility_permissions_user_id");

                    b.HasIndex("Role", "AccessLevel")
                        .HasDatabaseName("ix_facility_permissions_role_access_level");

                    b.HasIndex("OfficeId", "SpaceId", "UserId")
                        .HasDatabaseName("ix_facility_permissions_office_id_space_id_user_id");

                    b.ToTable("facility_permissions");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_offices");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_offices_tenant_id_status");

                    b.ToTable("offices");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text")
                        .HasColumnName("cost_center");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("LaborCategory")
                        .HasColumnType("text")
                        .HasColumnName("labor_category");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrgUnit")
                        .HasColumnType("text")
                        .HasColumnName("org_unit");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_people_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_people_user_id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_people_tenant_id_email");

                    b.ToTable("people");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.PersonCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("certification_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CredentialId")
                        .HasColumnType("text")
                        .HasColumnName("credential_id");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_person_certifications");

                    b.HasIndex("CertificationId")
                        .HasDatabaseName("ix_person_certifications_certification_id");

                    b.HasIndex("PersonId", "CertificationId")
                        .HasDatabaseName("ix_person_certifications_person_id_certification_id");

                    b.ToTable("person_certifications");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.PersonSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_person_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_person_skills_skill_id");

                    b.HasIndex("PersonId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_skills_person_id_skill_id");

                    b.ToTable("person_skills");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProgramCode")
                        .HasColumnType("text")
                        .HasColumnName("program_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ProgramCode")
                        .HasDatabaseName("ix_projects_program_code");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_projects_tenant_id_status");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowSelfRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_self_request");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("FteRequired")
                        .HasColumnType("numeric")
                        .HasColumnName("fte_required");

                    b.Property<string>("LaborCategory")
                        .HasColumnType("text")
                        .HasColumnName("labor_category");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("text")
                        .HasColumnName("required_skills");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("WbsElementId")
                        .HasDatabaseName("ix_project_roles_wbs_element_id");

                    b.HasIndex("TenantId", "WbsElementId", "Status")
                        .HasDatabaseName("ix_project_roles_tenant_id_wbs_element_id_status");

                    b.ToTable("project_roles");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalFields")
                        .HasColumnType("text")
                        .HasColumnName("additional_fields");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_section_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_entries");

                    b.HasIndex("ResumeSectionId")
                        .HasDatabaseName("ix_resume_entries_resume_section_id");

                    b.ToTable("resume_entries");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("TemplateConfig")
                        .HasColumnType("text")
                        .HasColumnName("template_config");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_profiles");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_resume_profiles_person_id");

                    b.ToTable("resume_profiles");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("ResumeProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_profile_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_resume_sections");

                    b.HasIndex("ResumeProfileId")
                        .HasDatabaseName("ix_resume_sections_resume_profile_id");

                    b.HasIndex("PersonId", "DisplayOrder")
                        .HasDatabaseName("ix_resume_sections_person_id_display_order");

                    b.ToTable("resume_sections");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_role_assignments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_role_assignments_user_id");

                    b.HasIndex("TenantId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_role_assignments_tenant_id_user_id_role");

                    b.ToTable("role_assignments");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingRules")
                        .HasColumnType("text")
                        .HasColumnName("booking_rules");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DailyCost")
                        .HasColumnType("numeric")
                        .HasColumnName("daily_cost");

                    b.Property<string>("Equipment")
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("Features")
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_user_id");

                    b.Property<int?>("MaxBookingDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_booking_days");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("OfficeId")
                        .HasDatabaseName("ix_spaces_office_id");

                    b.HasIndex("ManagerUserId", "IsActive")
                        .HasDatabaseName("ix_spaces_manager_user_id_is_active");

                    b.HasIndex("TenantId", "OfficeId", "Type")
                        .HasDatabaseName("ix_spaces_tenant_id_office_id_type");

                    b.ToTable("spaces");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.SpaceMaintenanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_space_maintenance_logs");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_space_maintenance_logs_assigned_to_user_id");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_space_maintenance_logs_reported_by_user_id");

                    b.HasIndex("ScheduledDate", "Status")
                        .HasDatabaseName("ix_space_maintenance_logs_scheduled_date_status");

                    b.HasIndex("SpaceId", "Status")
                        .HasDatabaseName("ix_space_maintenance_logs_space_id_status");

                    b.ToTable("space_maintenance_logs");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_tenant_memberships_tenant_id_is_active");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_user_id_tenant_id");

                    b.ToTable("tenant_memberships");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_object_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_admin");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_photo_url");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_object_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invitation_token");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_invitations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_invitations_tenant_id");

                    b.ToTable("user_invitations");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.WbsChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("WbsElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("wbs_element_id");

                    b.HasKey("Id")
                        .HasName("pk_wbs_change_history");

                    b.HasIndex("ChangedById")
                        .HasDatabaseName("ix_wbs_change_history_changed_by_id");

                    b.HasIndex("WbsElementId")
                        .HasDatabaseName("ix_wbs_change_history_wbs_element_id");

                    b.ToTable("wbs_change_history");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.WbsElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text")
                        .HasColumnName("approval_notes");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_id");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_user_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_billable");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_wbs_elements");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_wbs_elements_approver_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_wbs_elements_owner_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_wbs_elements_project_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_wbs_elements_tenant_id_code");

                    b.ToTable("wbs_elements");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Assignment", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments__users_approved_by_user_id");

                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithMany("Assignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__people_person_id");

                    b.HasOne("MyScheduling.Core.Entities.ProjectRole", "ProjectRole")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments__project_roles_project_role_id");

                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__tenants_tenant_id");

                    b.HasOne("MyScheduling.Core.Entities.WbsElement", "WbsElement")
                        .WithMany("Assignments")
                        .HasForeignKey("WbsElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments__wbs_elements_wbs_element_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Person");

                    b.Navigation("ProjectRole");

                    b.Navigation("Tenant");

                    b.Navigation("WbsElement");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.AssignmentHistory", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Assignment", "Assignment")
                        .WithMany("History")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_history_assignments_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Booking", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithMany("Bookings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__people_person_id");

                    b.HasOne("MyScheduling.Core.Entities.Space", "Space")
                        .WithMany("Bookings")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__spaces_space_id");

                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings__tenants_tenant_id");

                    b.Navigation("Person");

                    b.Navigation("Space");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.CheckInEvent", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Booking", "Booking")
                        .WithMany("CheckInEvents")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_events_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.FacilityPermission", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_facility_permissions__offices_office_id");

                    b.HasOne("MyScheduling.Core.Entities.Space", "Space")
                        .WithMany("Permissions")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_facility_permissions__spaces_space_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_facility_permissions__users_user_id");

                    b.Navigation("Office");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Office", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offices__tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Person", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany("People")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_people__tenants_tenant_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_people__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.PersonCertification", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Certification", "Certification")
                        .WithMany("PersonCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_certifications_certifications_certification_id");

                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithMany("PersonCertifications")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_certifications_people_person_id");

                    b.Navigation("Certification");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.PersonSkill", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithMany("PersonSkills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_skills_people_person_id");

                    b.HasOne("MyScheduling.Core.Entities.Skill", "Skill")
                        .WithMany("PersonSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_skills__skills_skill_id");

                    b.Navigation("Person");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Project", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects__tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ProjectRole", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_roles__tenants_tenant_id");

                    b.HasOne("MyScheduling.Core.Entities.WbsElement", "WbsElement")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("WbsElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_roles__wbs_elements_wbs_element_id");

                    b.Navigation("Tenant");

                    b.Navigation("WbsElement");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeEntry", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.ResumeSection", "ResumeSection")
                        .WithMany("Entries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_entries__resume_sections_resume_section_id");

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeProfile", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithOne("ResumeProfile")
                        .HasForeignKey("MyScheduling.Core.Entities.ResumeProfile", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_profiles_people_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeSection", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_sections_people_person_id");

                    b.HasOne("MyScheduling.Core.Entities.ResumeProfile", null)
                        .WithMany("Sections")
                        .HasForeignKey("ResumeProfileId")
                        .HasConstraintName("fk_resume_sections_resume_profiles_resume_profile_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.RoleAssignment", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments__tenants_tenant_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_assignments__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Space", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_spaces__users_manager_user_id");

                    b.HasOne("MyScheduling.Core.Entities.Office", "Office")
                        .WithMany("Spaces")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_offices_office_id");

                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spaces__tenants_tenant_id");

                    b.Navigation("Manager");

                    b.Navigation("Office");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.SpaceMaintenanceLog", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_space_maintenance_logs__users_assigned_to_user_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_space_maintenance_logs__users_reported_by_user_id");

                    b.HasOne("MyScheduling.Core.Entities.Space", "Space")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_space_maintenance_logs_spaces_space_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("ReportedBy");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.TenantMembership", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships__users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.User", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", null)
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.UserInvitation", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_invitations_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.WbsChangeHistory", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_change_history_users_changed_by_id");

                    b.HasOne("MyScheduling.Core.Entities.WbsElement", "WbsElement")
                        .WithMany("ChangeHistory")
                        .HasForeignKey("WbsElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_change_history__wbs_elements_wbs_element_id");

                    b.Navigation("ChangedBy");

                    b.Navigation("WbsElement");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.WbsElement", b =>
                {
                    b.HasOne("MyScheduling.Core.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .HasConstraintName("fk_wbs_elements_users_approver_id");

                    b.HasOne("MyScheduling.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_wbs_elements_users_owner_id");

                    b.HasOne("MyScheduling.Core.Entities.Project", "Project")
                        .WithMany("WbsElements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_elements_projects_project_id");

                    b.HasOne("MyScheduling.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wbs_elements_tenants_tenant_id");

                    b.Navigation("Approver");

                    b.Navigation("Owner");

                    b.Navigation("Project");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Assignment", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Booking", b =>
                {
                    b.Navigation("CheckInEvents");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Certification", b =>
                {
                    b.Navigation("PersonCertifications");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Office", b =>
                {
                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Person", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Bookings");

                    b.Navigation("PersonCertifications");

                    b.Navigation("PersonSkills");

                    b.Navigation("ResumeProfile");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Project", b =>
                {
                    b.Navigation("WbsElements");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ProjectRole", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeProfile", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.ResumeSection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Skill", b =>
                {
                    b.Navigation("PersonSkills");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Space", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.Tenant", b =>
                {
                    b.Navigation("People");

                    b.Navigation("TenantMemberships");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.User", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("TenantMemberships");
                });

            modelBuilder.Entity("MyScheduling.Core.Entities.WbsElement", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ChangeHistory");

                    b.Navigation("ProjectRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
